# Site
name: 'PythonMood'
description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
email: 'lucbertin@outlook.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    luc:
      name:           Luc
      site:           https://lucbertin.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, my name is Luc. To me, code is art and i love coding in Python, hence the website !"
      email:          contact@lucbertin.com
      github:         https://github.com/Luc-Bertin
      medium:         https://medium.com/@lucbtn
      linkedin:       https://www.linkedin.com/in/luc-b-291904ab/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Luc
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]